### ISSUE TITLE
Population distribution panel is scaled too small sometimes

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Infixo/CS2-InfoLoom#6]
![Snipaste_2024-01-19_05-19-10](https://github.com/Infixo/CS2-InfoLoom/assets/31107435/6c675e53-f140-44b5-8d08-75e52a74f490)

**Comment by Infixo** [comment]
Well, scaling unfortunately is not ideal due to some technical limitations. Those vertical lines are "fixed" so as for now, the bars scale at 10, 100, 1000 and 10000. So when the scale changes, those bars are 10x smaller.

**Comment by GIS-PuppetMaster** [comment]
> Well, scaling unfortunately is not ideal due to some technical limitations. Those vertical lines are "fixed" so as for now, the bars scale at 10, 100, 1000 and 10000. So when the scale changes, those bars are 10x smaller.不幸的是，由于一些技术限制，扩展并不理想。这些垂直线是“固定的”，因此目前，条形的比例为 10、100、1000 和 10000。因此，当比例发生变化时，这些条形会缩小 10 倍。

maybe setting more scale levels will help to prevent this problem?

**Comment by Infixo** [comment]
> maybe setting more scale levels will help to prevent this problem?
Well, partially. The issue is that those vertical lines are fixed, and they shoud me meaningful.

The mod can make full scaling e.g. longest bar would always take 100% of the window, but that way I need to remove vertical lines - they don't update well.
I chose to have these vertical lines because numbers on lower resolutions like 1080p are not easily readable. So, you can have sort of visual measurement.

Idk yet which solution is better. As for now I am trying to mix them, so lines mean something but also bars scale.

**Comment by Infixo** [comment]
v0.8 is now available and it has a dynamic scaling.
