### ISSUE TITLE
Number of homeless people is displayed differently in this mod

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Infixo/CS2-InfoLoom#7]
![image](https://github.com/Infixo/CS2-InfoLoom/assets/31107435/8d1dcefa-444a-47fd-ac13-e17853b305e5)
The text in the red box means Homeless in English, you can see they show different value, I think the lower is more reasonable since the unemployment rate is only 3.5%.

**Comment by Infixo** [comment]
On the left, Residential Demand is homeless households, including commuters and tourists
On the right, Demographics is homless citizens but only within actual citizens, so no commuters and tourists
These are different things and counted differently because they are used in different places in the game
Residential Demand - this is how demand is calculated
Demographics - this is just population view based on citizens

**Comment by Infixo** [comment]
Yeah.. I know it can be confusing but this game IS VERY COMPLEX at its foundation. There are a lot data with different purpose and lots of systems that use it differently. The game's base UI simply doesn't show this complexity.

Bascially, all of these: homeless, unemployed, movedin, moving away, commuter, tourist, household, citizen, student, etc. ALL OF THESE data are separate data that can mix virtually in all combinations.

**Comment by GIS-PuppetMaster** [comment]
> On the left, Residential Demand is homeless households, including commuters and tourists左边，住宅需求是无家可归的家庭，包括通勤者和游客 On the right, Demographics is homless citizens but only within actual citizens, so no commuters and tourists 右边，人口统计是无家可归的公民，但仅限于实际公民，因此没有通勤者和游客 These are different things and counted differently because they are used in different places in the game 这些是不同的东西，并且计数也不同，因为它们在游戏中的不同地方使用 Residential Demand - this is how demand is calculated 住宅需求——这就是需求的计算方式 Demographics - this is just population view based on citizens 人口统计——这只是基于公民的人口观点

Got it, the same as I understand after reading your patient explanation on discord, thanks!
